// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Softqu.Infrastructure.Data;

#nullable disable

namespace Softqu.Infrastucture.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Softqu.Domain.Category.CategoryAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Softqu.Domain.Category.Entities.CategoryTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryTranslations", (string)null);
                });

            modelBuilder.Entity("Softqu.Domain.PopularCategory.PopularCategoryAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .IsUnique();

                    b.ToTable("PopularCategories", (string)null);
                });

            modelBuilder.Entity("Softqu.Domain.SwiperSlide.SwiperSlideAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SwiperSlides", (string)null);
                });

            modelBuilder.Entity("Softqu.Domain.Category.CategoryAggregate", b =>
                {
                    b.HasOne("Softqu.Domain.Category.CategoryAggregate", null)
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Softqu.Domain.Category.Entities.CategoryTranslation", b =>
                {
                    b.HasOne("Softqu.Domain.Category.CategoryAggregate", null)
                        .WithMany("Translations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Softqu.Domain.PopularCategory.PopularCategoryAggregate", b =>
                {
                    b.HasOne("Softqu.Domain.Category.CategoryAggregate", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Softqu.Domain.SwiperSlide.SwiperSlideAggregate", b =>
                {
                    b.HasOne("Softqu.Domain.Category.CategoryAggregate", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Softqu.Domain.SwiperSlide.Entities.SwiperSlideTranslation", "Translations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("LanguageCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("SwiperSlideId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("SwiperSlideId");

                            b1.ToTable("SwiperSlideTranslations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SwiperSlideId");

                            b1.OwnsOne("Softqu.Domain.SwiperSlide.ValueObjects.HighlightedTitle", "Title", b2 =>
                                {
                                    b2.Property<Guid>("SwiperSlideTranslationId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("BoldHighlight")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ColorHighlight")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("NormalText")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("SwiperSlideTranslationId");

                                    b2.ToTable("SwiperSlideTranslations");

                                    b2.WithOwner()
                                        .HasForeignKey("SwiperSlideTranslationId");
                                });

                            b1.OwnsOne("Softqu.Domain.SwiperSlide.ValueObjects.SlideTexts", "Texts", b2 =>
                                {
                                    b2.Property<Guid>("SwiperSlideTranslationId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("BigTitle")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("BottomText")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("TopText")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("SwiperSlideTranslationId");

                                    b2.ToTable("SwiperSlideTranslations");

                                    b2.WithOwner()
                                        .HasForeignKey("SwiperSlideTranslationId");
                                });

                            b1.Navigation("Texts")
                                .IsRequired();

                            b1.Navigation("Title")
                                .IsRequired();
                        });

                    b.Navigation("Category");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Softqu.Domain.Category.CategoryAggregate", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
